### ISSUE TITLE
How to Custom Text Input Field in FormWidget

### ISSUE THREAD

**Issue by bobwatcherx** [Almas-Ali/fronty#1]
can you give a more complete example regarding the formwidget and how to customize the input and how to submit it

Body(
            FormWidget(load_css=True),

**Comment by Almas-Ali** [comment]
Check this page for more attribute details of `FormWidget()`
https://almas-ali.github.io/fronty/widgets/attributes.html

**Comment by Almas-Ali** [comment]
New URL has been updated to -> https://almas-ali.github.io/fronty/latest/widgets/attributes.html
