### ISSUE TITLE
cannot import CSS i get errr 

### ISSUE THREAD

**Issue by bobwatcherx** [Almas-Ali/fronty#2]
**this error**
    from fronty.css import CSS, Selector, Style
ImportError: cannot import name 'Style' from 'fronty.css' (/usr/local/lib/python3.10/dist-packages/fronty/css/__init__.py)
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/fronty# python3 main.py 
Traceback (most recent call last):
  File "/home/miop/belajar/fronty/main.py", line 4, in <module>
    from fronty.css import CSS, Selector, Style
ImportError: cannot import name 'Style' from 'fronty.css' (/usr/local/lib/python3.10/dist-packages/fronty/css/__init__.py

**Comment by Almas-Ali** [comment]
Your tring to import Style from `fronty.css` but it is in `fronty.html` because it is a HTML tag so we have defined it in `fronty.html`
