### ISSUE TITLE
How to Buton click , on_click not work

### ISSUE THREAD

**Issue by bobwatcherx** [Almas-Ali/fronty#3]
my code

def runapp():
        print("Dqdqdw")

Button("insert hew",on_click=runapp)

**Comment by Almas-Ali** [comment]
It is not implemented yet. I will add this feature in next release.

Thank you for mentioning this issue.

**Comment by Almas-Ali** [comment]
This issue feature has been implemented in the module `fronty.js`. You can use this like the [example/Action button/app.py](https://github.com/Almas-Ali/fronty/blob/master/examples/Action%20button/app.py).  Docs will be re-written when the module will be ready.
